### ISSUE TITLE
Modul ist nicht PHP7 kompatibel

### ISSUE THREAD

**Issue by bschi** [contao-community-alliance/twig#15]
Die Erweiterung unterstützt aktuell kein PHP7.
Siehe auch https://github.com/contao/core/commit/5cc52edd9291784907ba1806101bb95f6ef253dc

``` php
Uncaught exception 'Error' with message 'Function name must be a string' thrown in C:\Bitnami\apache2\htdocs\danceyou\composer\vendor\contao-community-alliance\contao-twig\src\ContaoTwig\TwigBackendTemplate.php on line 47
#0 C:\Bitnami\apache2\htdocs\danceyou\composer\vendor\contao-community-alliance\contao-twig\src\ContaoTwig\TwigBackendModule.php(44): TwigBackendTemplate->parse()
#1 C:\Bitnami\apache2\htdocs\danceyou\composer\vendor\bit3\contao-assetic\src\ContaoAssetic\AsseticConfigModule.php(65): TwigBackendModule->generate()
#2 C:\Bitnami\apache2\htdocs\danceyou\system\modules\core\classes\Backend.php(423): ContaoAssetic\AsseticConfigModule->generate()
#3 C:\Bitnami\apache2\htdocs\danceyou\system\modules\core\controllers\BackendMain.php(131): Contao\Backend->getBackendModule('assetic_config')
#4 C:\Bitnami\apache2\htdocs\danceyou\contao\main.php(20): Contao\BackendMain->run()
```

**Comment by rflx** [comment]
+1
